apiVersion: v1
kind: Service
metadata:
    namespace: staging
    labels:
        run: frontend-svc
    name: frontend-svc
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer