apiVersion: v1
kind: Service
metadata:
    namespace: staging
    labels:
        run: frontend-svc
    name: frontend-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer