apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - image: mansong/imageclassifier-frontend
                  imagePullPolicy: IfNotPresent
                  name: imageclassifier-frontend
                  ports:
                        - containerPort: 80
                  volumeMounts:
                      - name: frontend-config-volume
                        mountPath: /usr/share/nginx/html/config.js
                        subPath: config.js
                        readOnly: true
            volumes:
                - name: frontend-config-volume
                  configMap:
                      name: frontend-config

                    
                