apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resnet-deployment
  namespace: staging
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      containers:
      - name: resnet-container
        image: mansong/resnet_tfserving
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  labels:
    run: resnet-service
  name: resnet-service
spec:
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: resnet-server
  type: LoadBalancer