apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resnet-deployment
  namespace: staging
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      containers:
      - name: resnet-container
        image: mansong/resnet_tfserving:3
        env:
          - name: TENSORFLOW_INTRA_OP_PARALLELISM
            value: '4'
          - name: TENSORFLOW_INTER_OP_PARALLELISM
            value: '4'
        resources:
          requests:
            memory: "1Gi"
            cpu: "1Gi"
          limits:
            memory: "5Gi"
            cpu: "5Gi"
        ports:
        - containerPort: 8500