apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: KubernetesCluster
  region: us-west-2

managedNodeGroups:
  - name: managed-1
    instanceType: m5.large
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: false
    labels: {role: worker}
    iam:
      instanceRoleARN: "arn:aws:iam::803823249935:role/AmazonEKS-NodeGroupRole"
