apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resnet-deployment
  namespace: staging
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      containers:
      - name: resnet-container
        image: mansong/resnet_tfserving:35
        env:
        - name: TENSORFLOW_INTRA_OP_PARALLELISM
          value: '4'
        - name: TENSORFLOW_INTER_OP_PARALLELISM
          value: '4'
        ports:
        - containerPort: 8500
