apiVersion: v1
kind: Service
metadata:
    namespace: staging
    labels:
        run: api-svc
    name: api-svc
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
    selector:
        app: api
    type: ClusterIP